import json
import random
import uuid
import asyncio
from pathlib import Path
from typing import List, Dict, Any

from openai import AsyncOpenAI

# Import configs from MiroFish core
from core.config import LLM
from core.population import generate_demographic, save_population

client = AsyncOpenAI(
    api_key=LLM.api_key,
    base_url=LLM.base_url,
)

async def generate_personality_for_agent(demo: Dict[str, Any], semaphore: asyncio.Semaphore) -> Dict[str, Any]:
    """Use LLM to generate a unique base personality based on demographics."""
    async with semaphore:
        prompt = (
            f"สร้างคำอธิบายลักษณะนิสัยสั้นๆ (1-2 ประโยค) สำหรับประชากรไทยที่มีข้อมูลดังนี้:\n"
            f"- อายุ: {demo['age']} ปี\n"
            f"- อาชีพ: {demo['occupation']}\n"
            f"- ภูมิภาค: {demo['region']}\n"
            f"- การศึกษา: {demo['education']}\n"
            f"- การเข้าถึงสื่อโซเชียล: {'เข้าถึง' if demo['media']['social_media'] else 'ไม่เล่นโซเชียล'}\n\n"
            f"ตัวอย่างคำตอบ: 'เป็นคนหัวก้าวหน้า ชอบตั้งคำถามกับสังคมและตามข่าวในทวิตเตอร์ตลอดเวลา'"
        )
        
        try:
            response = await client.chat.completions.create(
                model=LLM.model,
                messages=[{"role": "user", "content": prompt}],
                max_tokens=100,
                temperature=0.8
            )
            personality = response.choices[0].message.content.strip()
            demo["base_personality"] = personality
        except Exception as e:
            print(f"Error generating personality for {demo['agent_id']}: {e}")
            demo["base_personality"] = "" # Fallback if API fails
            
        return demo

async def generate_large_population_async(num_agents: int = 1000):
    print(f"🚀 Generating {num_agents} unique agents (Demographics + LLM Personality)...")
    rng = random.Random(42)
    
    # 1. Generate Base Demographics (No Hardcoding)
    agents_demo = []
    for _ in range(num_agents):
        agent_id = f"agent_{uuid.uuid4().hex[:6]}"
        demo = generate_demographic(rng, agent_id)
        agents_demo.append(demo)
        
    print(f"✅ Demographics generated. Now querying {LLM.model} for personalities...")
    
    # 2. Generate Personalities via LLM concurrently
    # Limit concurrency to avoid rate limits on OpenRouter
    semaphore = asyncio.Semaphore(LLM.concurrency) 
    
    tasks = [generate_personality_for_agent(demo, semaphore) for demo in agents_demo]
    agents_completed = await asyncio.gather(*tasks)
    
    # 3. Save to file
    out_path = Path(__file__).parent / "data" / "population_200.json"
    save_population(agents_completed, str(out_path), metadata={"description": f"{num_agents} unique agents generated by LLM"})
    print(f"🎉 Successfully saved {num_agents} fully unique agents to {out_path}")

def generate_large_population(num_agents: int = 1000):
    asyncio.run(generate_large_population_async(num_agents))

if __name__ == "__main__":
    import sys
    num = 1000
    if len(sys.argv) > 1:
        num = int(sys.argv[1])
    generate_large_population(num)
